"""Evidence bundle helpers (Python orchestration; Lean checker is separate).

Default layout is Evidence Bundle **v0.2**: canonical ``.cjson`` bytes for
theorem-binding roles. v0.1 pretty ``.json`` bundles remain readable.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from adapters.common.canonical import canonical_dumps, sha256_digest, sha256_hex
from adapters.common.schema_validate import SchemaStore

BUNDLE_VERSION = "0.2.0"
BUNDLE_VERSION_LEGACY = "0.1.0"

# Theorem-binding roles written as canonical JSON (no pretty whitespace).
V02_CJSON_ROLES = (
    "request",
    "candidate",
    "certificate",
    "manifest",
    "checker-receipt",
    "axiom-report",
)

VERIFIED_RESULT_STATUSES = frozenset(
    {
        "witness_verified",
        "soundness_verified",
        "completeness_verified",
        "optimality_verified",
        "native_verified",
    }
)


def file_digest(path: Path) -> str:
    data = path.read_bytes()
    return "sha256:" + sha256_hex(data)


def write_json(path: Path, obj: Any) -> None:
    """Pretty JSON for non-binding / human renderings only."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_cjson(path: Path, obj: Any) -> None:
    """Canonical JSON bytes (mathevidence-jcs-0.2) for theorem-binding files."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(canonical_dumps(obj), encoding="utf-8")


def find_role_path(bundle_dir: Path, stem: str) -> Path | None:
    """Prefer v0.2 ``.cjson`` then legacy ``.json`` for a bundle role stem."""
    cjson = bundle_dir / f"{stem}.cjson"
    if cjson.is_file():
        return cjson
    json_path = bundle_dir / f"{stem}.json"
    if json_path.is_file():
        return json_path
    return None


def load_role_json(bundle_dir: Path, stem: str) -> dict[str, Any]:
    path = find_role_path(bundle_dir, stem)
    if path is None:
        raise FileNotFoundError(f"missing bundle role {stem}.cjson/{stem}.json under {bundle_dir}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path.name} must contain a JSON object")
    return data


def iter_bundle_dirs(root: Path) -> list[Path]:
    """Unique bundle directories under ``root`` that have a manifest role (``.cjson`` or ``.json``)."""
    if not root.is_dir():
        return []
    seen: set[Path] = set()
    bundles: list[Path] = []
    for pattern in ("manifest.cjson", "manifest.json"):
        for path in root.rglob(pattern):
            parent = path.parent.resolve()
            if parent in seen:
                continue
            if find_role_path(parent, "manifest") is None:
                continue
            seen.add(parent)
            bundles.append(parent)
    return sorted(bundles)


def build_manifest(
    *,
    capability_id: str,
    capability_version: str,
    request_digest: str,
    claim_class: str,
    result_status: str,
    assurance_mode: str,
    files: list[dict[str, str]],
    provenance: dict[str, Any],
    bundle_version: str = BUNDLE_VERSION,
) -> dict[str, Any]:
    return {
        "bundleVersion": bundle_version,
        "capability": {"id": capability_id, "version": capability_version},
        "requestDigest": request_digest,
        "claimClass": claim_class,
        "resultStatus": result_status,
        "assuranceMode": assurance_mode,
        "files": files,
        "provenance": provenance,
    }


def _default_axiom_report(*, lean_version: str, library_revision: str) -> dict[str, Any]:
    return {
        "schemaVersion": "0.2.0",
        "status": "pending_compiled_audit",
        "leanVersion": lean_version,
        "libraryRevision": library_revision,
        "findings": [],
        "detail": "Placeholder axiom report; compiled Lake audit is authoritative.",
    }


def _default_theorem_lean(*, capability: str, request_digest: str) -> str:
    return (
        "-- Autogenerated theorem stub for Evidence Bundle v0.2.\n"
        "-- Ordinary goals are closed by Lean tactic / mathevidence-replay authority;\n"
        "-- this file is a content-addressed role, not an independent closer.\n"
        f"-- capability: {capability}\n"
        f"-- requestDigest: {request_digest}\n"
        "theorem mathevidence_bundle_theorem_placeholder : True := trivial\n"
    )


def write_bundle(
    bundle_dir: Path,
    *,
    request: dict[str, Any],
    candidate: dict[str, Any],
    certificate: dict[str, Any],
    result_status: str = "computed",
    claim_class: str = "candidate",
    assurance_mode: str = "kernel_replay",
    lean_version: str = "4.x-pending",
    library_revision: str = "workspace",
    checker_version: str = "0.1.0",
    readme: str | None = None,
    schemas: SchemaStore | None = None,
    checker_receipt: dict[str, Any] | None = None,
    axiom_report: dict[str, Any] | None = None,
    theorem_lean: str | None = None,
) -> dict[str, Any]:
    """Write an Evidence Bundle v0.2 directory and return the manifest.

    Manifest MUST NOT advertise a verified ``resultStatus`` unless
    ``checker_receipt`` establishes ``claimEstablished``.
    """
    store = schemas or SchemaStore()
    cap = request.get("capability")
    req_schema, cert_schema = _schemas_for_capability(cap if isinstance(cap, str) else "")
    store.validate(req_schema, request)
    store.validate(cert_schema, certificate)

    # Honesty: never claim verified from packaging alone.
    if result_status in VERIFIED_RESULT_STATUSES and checker_receipt is None:
        result_status = "computed"
    if checker_receipt is not None:
        established = checker_receipt.get("claimEstablished")
        if established is None and result_status in VERIFIED_RESULT_STATUSES:
            result_status = "computed"

    bundle_dir.mkdir(parents=True, exist_ok=True)
    write_cjson(bundle_dir / "request.cjson", request)
    write_cjson(bundle_dir / "candidate.cjson", candidate)
    write_cjson(bundle_dir / "certificate.cjson", certificate)

    axiom = axiom_report or _default_axiom_report(
        lean_version=lean_version, library_revision=library_revision
    )
    write_cjson(bundle_dir / "axiom-report.cjson", axiom)

    thm = theorem_lean or _default_theorem_lean(
        capability=str(cap),
        request_digest=str(request.get("requestDigest", "")),
    )
    (bundle_dir / "theorem.lean").write_text(thm, encoding="utf-8")

    if checker_receipt is not None:
        write_cjson(bundle_dir / "checker-receipt.cjson", checker_receipt)

    if readme is None:
        readme = (
            f"# Evidence bundle (v0.2)\n\n"
            f"Canonical `.cjson` roles for `{cap}`.\n"
            "Adapter output is untrusted; Lean checkers own theorem acceptance.\n"
            "Legacy pretty `.json` bundles remain readable via dual-path verify.\n"
        )
    (bundle_dir / "README.md").write_text(readme, encoding="utf-8")

    relative_files = [
        "request.cjson",
        "candidate.cjson",
        "certificate.cjson",
        "axiom-report.cjson",
        "theorem.lean",
        "README.md",
    ]
    if checker_receipt is not None:
        relative_files.insert(3, "checker-receipt.cjson")

    files_meta: list[dict[str, str]] = []
    for name in relative_files:
        path = bundle_dir / name
        if name.endswith(".md"):
            media = "text/markdown"
        elif name.endswith(".lean"):
            media = "text/x-lean"
        elif name.endswith(".cjson"):
            media = "application/cjson"
        else:
            media = "application/json"
        files_meta.append(
            {
                "path": name,
                "digest": file_digest(path),
                "mediaType": media,
            }
        )

    manifest = build_manifest(
        capability_id=request["capability"],
        capability_version=request["capabilityVersion"],
        request_digest=request["requestDigest"],
        claim_class=claim_class,
        result_status=result_status,
        assurance_mode=assurance_mode,
        files=files_meta,
        provenance={
            "leanVersion": lean_version,
            "libraryRevision": library_revision,
            "checkerVersion": checker_version,
            "backend": certificate.get("provenance"),
        },
        bundle_version=BUNDLE_VERSION,
    )
    store.validate("evidence-bundle.schema.json", manifest)
    write_cjson(bundle_dir / "manifest.cjson", manifest)
    return manifest


def _schemas_for_capability(capability: str) -> tuple[str, str]:
    if capability == "algebra.linear_algebra":
        return (
            "linear-algebra-request.schema.json",
            "linear-algebra-certificate.schema.json",
        )
    if capability == "logic.finite_counterexample":
        return (
            "finite-counterexample-request.schema.json",
            "finite-counterexample-certificate.schema.json",
        )
    if capability == "algebra.formal_rational_calculus":
        return (
            "symbolic-calculus-request.schema.json",
            "symbolic-calculus-certificate.schema.json",
        )
    if capability == "algebra.groebner_membership":
        return (
            "ideal-membership-request.schema.json",
            "ideal-membership-certificate.schema.json",
        )
    return (
        "rational-equality-request.schema.json",
        "rational-equality-certificate.schema.json",
    )


def verify_bundle_offline(bundle_dir: Path, *, schemas: SchemaStore | None = None) -> list[str]:
    """Validate schemas + digests without starting backends. Returns warnings.

    Accepts v0.2 ``.cjson`` and legacy v0.1 ``.json`` layouts.
    """
    store = schemas or SchemaStore()
    warnings: list[str] = []
    manifest_path = find_role_path(bundle_dir, "manifest")
    if manifest_path is None:
        raise FileNotFoundError(f"missing manifest.cjson/manifest.json under {bundle_dir}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    store.validate("evidence-bundle.schema.json", manifest)

    version = manifest.get("bundleVersion")
    if version not in {BUNDLE_VERSION, BUNDLE_VERSION_LEGACY}:
        warnings.append(f"unexpected bundleVersion {version!r}")

    from adapters.common.errors import AdapterError
    from adapters.common.security_bounds import reject_path_traversal

    for entry in manifest["files"]:
        rel = entry["path"]
        try:
            reject_path_traversal(rel, root=bundle_dir)
        except AdapterError as exc:
            raise ValueError(str(exc)) from exc
        # Manifest self-entries are rare; verify any listed path uniformly.
        path = bundle_dir / rel
        if not path.is_file():
            raise FileNotFoundError(f"missing bundle file: {rel}")
        actual = file_digest(path)
        if actual != entry["digest"]:
            raise ValueError(f"digest mismatch for {rel}: {actual} != {entry['digest']}")

    request = load_role_json(bundle_dir, "request")
    certificate = load_role_json(bundle_dir, "certificate")
    cap = request.get("capability", "")
    req_schema, cert_schema = _schemas_for_capability(cap if isinstance(cap, str) else "")
    store.validate(req_schema, request)
    store.validate(cert_schema, certificate)

    if request["requestDigest"] != manifest["requestDigest"]:
        raise ValueError("manifest.requestDigest != request.requestDigest")
    if certificate["requestDigest"] != request["requestDigest"]:
        raise ValueError("certificate.requestDigest != request.requestDigest")

    # Manifest must not claim verified without a receipt role.
    if manifest.get("resultStatus") in VERIFIED_RESULT_STATUSES:
        receipt_path = find_role_path(bundle_dir, "checker-receipt")
        if receipt_path is None:
            raise ValueError(
                "manifest claims verified status without checker-receipt.cjson/json"
            )

    from adapters.common.canonical import verify_request_digest
    from adapters.common.lean_mirrors import (
        check_finite_counterexample,
        check_linear_algebra,
        check_symbolic_calculus,
    )

    try:
        verify_request_digest(request)
    except Exception as exc:  # noqa: BLE001
        raise ValueError(f"request digest verification failed: {exc}") from exc

    if cap == "algebra.linear_algebra":
        if not check_linear_algebra(request, certificate):
            warnings.append("Python linear-algebra checker mirror rejected certificate")
    elif cap == "logic.finite_counterexample":
        if not check_finite_counterexample(request, certificate):
            warnings.append("Python finite-counterexample checker mirror rejected certificate")
    elif cap == "algebra.formal_rational_calculus":
        if not check_symbolic_calculus(request, certificate):
            warnings.append("Python symbolic-calculus checker mirror rejected certificate")

    _ = canonical_dumps
    _ = sha256_digest
    return warnings
